export const subjects = [
  {
    title: "CSI - Introduction to computing",
    description:
      "This course provides an overview of computer Fundamentals. Topics cover all areas of computer science in breadth such as computer organization, network, operating system, data structure, file structure, social and ethical issues.",
  },
  {
    title: "CEA - Computer Organization and Architecture",
    description:
      "This course in an introduction to computer architecture and organization. It will cover topics in both the physical design of the computer (organization) and the logical design of the computer (architecture). The main contents include the organization of a simple stored-program computer: CPU, busses and memory; Instruction sets, machine code, and assembly language; Conventions for assembly language generated by compilers; Floating-point number representation; Hardware organization of simple processors; Address translation and virtual memory; Very introductory examples of input/output devices, interrupt handling and multi-tasking systems.",
  },
  {
    title: "PRF - Programming Fundamentals",
    description:
      "Understand basics computer system and methods of software development, focus on function-oriented programming design, coding, testing and discipline in programming. Explain basic concepts of programming, function-oriented programming design, modularity, understand and coding programs using C language.",
  },
  {
    title: "PRO - Object-Oriented Programming",
    description:
      "This course introduces the concepts of object-oriented programming and design. It covers the principles of object-oriented programming, including encapsulation, inheritance, polymorphism, and abstraction. The course emphasizes the use of Java as an object-oriented programming language.",
  },
  {
    title: "OSG - Operating Systems",
    description:
      "This course provides an introduction to the fundamental concepts of operating systems. It covers topics such as process management, memory management, file systems, and system security. The course emphasizes the design and implementation of operating systems.",
  },
  {
    title: "NWC - Computer Networking",
    description:
      "This course provides an introduction to the principles and practices of computer networking. It covers topics such as network architecture, protocols, routing, switching, and security. The course emphasizes the design and implementation of computer networks.",
  },
  {
    title: "WED - Web Design",
    description:
      "This course provides an introduction to web design and development. It covers topics such as HTML, CSS, JavaScript, and responsive design. The course emphasizes the design and implementation of user-friendly web interfaces.",
  },
  {
    title: "WDU - The UI/UX Design",
    description:
      "This course provides an introduction to user interface (UI) and user experience (UX) design. It covers topics such as user-centered design, usability testing, and interaction design. The course emphasizes the importance of designing user-friendly interfaces.",
  },
  {
    title: "CSD - Data Structures and Algorithms",
    description:
      "This course provides an introduction to data structures and algorithms. It covers topics such as arrays, linked lists, stacks, queues, trees, and graphs. The course emphasizes the design and analysis of algorithms for solving computational problems.",
  },
  {
    title: "DBI - Database Systems",
    description:
      "This course provides an introduction to database systems. It covers topics such as relational databases, SQL, normalization, and transaction management. The course emphasizes the design and implementation of database systems.",
  },
  {
    title: "LAB - OOP with Java Lab",
    description:
      "This course provides practical experience in object-oriented programming using Java. It covers topics such as class design, inheritance, polymorphism, and exception handling. The course emphasizes hands-on programming exercises and projects.",
  },
  {
    title: "IOT - Internet of Things",
    description:
      "This course provides an introduction to the Internet of Things (IoT). It covers the concepts and principles of IoT, including IoT architecture, protocols, sensors, and data processing. The course emphasizes hands-on experience using Arduino and for IoT projects.",
  },
  {
    title: "PRJ - Java Web application development",
    description:
      "This course provides an introduction to web application development using Java. It covers topics such as servlets, JSP, MVC architecture, and web frameworks. The course emphasizes the design and implementation of dynamic web applications.",
  },
  {
    title: "SWE - Introduction to Software Engineering",
    description:
      "This course provides an introduction to software engineering principles and practices. It covers topics such as software development life cycle, requirements analysis, design, testing, and maintenance. The course emphasizes the importance of software quality and project management.",
  },
  {
    title: "SWR - Software Requirements",
    description:
      "This course provides an introduction to software requirements engineering. It covers topics such as requirements elicitation, analysis, specification, and validation. The course emphasizes the importance of clear and concise requirements in software development.",
  },
  {
    title: "SWT - Software Testing",
    description:
      "This course provides an introduction to software testing principles and practices. It covers topics such as test planning, test design, test execution, and defect management. The course emphasizes the importance of testing in ensuring software quality.",
  },
  {
    title: "SWD - Software Design",
    description:
      "This course provides an introduction to software design principles and practices. It covers topics such as design patterns, architectural styles, and design documentation. The course emphasizes the importance of good design in software development.",
  },
  {
    title: "SWP - Software Project",
    description:
      "This course provides practical experience in software development. Students work on a team project to design, implement, and test a software application. This was my first time developing a e-commercial web page using Next.js for the front end. The course emphasizes teamwork, communication, and project management skills.",
  },
  {
    title: "ITE - Ethics in Information Technology",
    description:
      "This course provides an introduction to ethical issues in information technology. It covers topics such as privacy, security, intellectual property, and professional ethics. The course emphasizes the importance of ethical decision-making in the field of information technology.",
  },
  {
    title: "PRN - Cross-Platform Application Programming With .NET",
    description:
      "This course provides an introduction to cross-platform application development using .NET. It covers topics such as .NET Core, ASP.NET, and Xamarin. The course emphasizes the design and implementation of cross-platform applications.",
  },
  {
    title: "PRM - Mobile Application Development",
    description:
      "This course provides an introduction to mobile application development. It covers topics such as mobile platforms, user interface design, and mobile application frameworks. The course emphasizes hands-on experience in developing mobile applications.",
  },
  {
    title: "PRU - C# Programming and Unity",
    description:
      "This course provides an introduction to C# programming and game development using Unity. It covers topics such as C# syntax, object-oriented programming, and game mechanics. The course emphasizes hands-on experience in developing games using Unity.",
  },
  {
    title: "PMG - Project Management",
    description:
      "This course provides an introduction to project management principles and practices. It covers topics such as project planning, scheduling, risk management, and quality assurance. The course emphasizes the importance of effective project management in software development.",
  },
  {
    title: "EXE - Experiential Entrepreneurship",
    description:
      "This course provides an introduction to entrepreneurship and innovation. It covers topics such as business models, market analysis, and funding strategies. The course emphasizes hands-on experience in developing a business plan and pitching to investors.",
  },
  {
    title: "SEP - Software Engineering Capstone Project",
    description:
      "This course provides practical experience in software engineering. Students work on a team project to design, implement, and test a software application. The course emphasizes teamwork, communication, and project management skills.",
  },
];
